services:
  booktracker:
    build: .
    container_name: booktracker-prod
    ports:
      - "80:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATA_FILE=/data/books.json
      - PORT=3000
    volumes:
      - booktracker-prod-data:/data
    labels:
      - "com.booktracker.description=BookTracker - Production Deployment"
      - "com.booktracker.version=2.0"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  booktracker-prod-data:
    driver: local
    labels:
      - "com.booktracker.description=Persistent storage for BookTracker production data"
