services:
  booktracker-api:
    build: ./backend
    container_name: booktracker-api
    ports:
      - "3001:3001"
    volumes:
      - booktracker-data:/app/data
      - booktracker-backups:/app/backups
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATA_DIR=/app/data
    labels:
      - "com.booktracker.description=BookTracker API - Backend Service with SQLite"
      - "com.booktracker.version=2.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - booktracker-network

  booktracker:
    build: .
    container_name: booktracker-app
    ports:
      - "8081:80"
    depends_on:
      - booktracker-api
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - API_URL=http://booktracker-api:3001
    labels:
      - "com.booktracker.description=BookTracker - Personal Book Collection Manager"
      - "com.booktracker.version=2.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - booktracker-network

volumes:
  booktracker-data:
    driver: local
  booktracker-backups:
    driver: local

networks:
  booktracker-network:
    driver: bridge
