services:
  booktracker:
    build: .
    container_name: booktracker-app
    ports:
      - "8081:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATA_FILE=/data/books.json
      - PORT=3000
    volumes:
      - booktracker-data:/data
    labels:
      - "com.booktracker.description=BookTracker - Personal Book Collection Manager with Data Persistence"
      - "com.booktracker.version=2.0"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  booktracker-data:
    driver: local
    labels:
      - "com.booktracker.description=Persistent storage for BookTracker data"
