
services:
  booktracker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: booktracker-prod
    ports:
      - "${PORT:-80}:80"
    restart: always
    environment:
      - NODE_ENV=production
      - NGINX_HOST=${NGINX_HOST:-localhost}
      - NGINX_PORT=${NGINX_PORT:-80}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booktracker.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.services.booktracker.loadbalancer.server.port=80"
      - "com.booktracker.description=BookTracker - Personal Book Collection Manager"
      - "com.booktracker.version=${APP_VERSION:-1.0.0}"
      - "com.booktracker.environment=production"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run

networks:
  default:
    name: booktracker-network
